'use client';

import { RegistrationFormValues } from '@/services/validator';
import { FileText, Printer, Download } from 'lucide-react';
import { useRef } from 'react';

interface InvoicePreviewProps {
  data: RegistrationFormValues;
}

export default function InvoicePreview({ data }: InvoicePreviewProps) {
  const invoiceRef = useRef<HTMLDivElement>(null);

  const handlePrintInvoice = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const html = [
      '<html><head><title>Tractor Invoice - ' + (data.invoiceNumber || 'DRAFT') + '</title>',
      '<style>',
      'body{font-family:Arial,sans-serif;padding:20px;color:#333}',
      '.container{max-width:800px;margin:0 auto;border:1px solid #ddd;padding:30px}',
      '.header{text-align:center;border-bottom:2px solid #2563eb;padding-bottom:15px;margin-bottom:20px}',
      '.header h1{color:#2563eb;margin:0;font-size:24px}',
      '.s-title{font-weight:bold;font-size:14px;background:#2563eb;color:white;padding:6px 12px;margin-bottom:8px}',
      '.s-title.green{background:#16a34a}',
      '.s-title.amber{background:#d97706}',
      '.s-title.purple{background:#9333ea}',
      '.row{display:flex;padding:4px 0;border-bottom:1px dashed #eee}',
      '.label{width:160px;font-weight:600;font-size:13px;color:#555}',
      '.value{flex:1;font-size:13px}',
      '.na{color:#aaa;font-style:italic}',
      '.g2{display:grid;grid-template-columns:1fr 1fr;gap:8px}',
      '.footer{text-align:center;margin-top:30px;font-size:11px;color:#888;border-top:1px solid #ddd;padding-top:10px}',
      '.v{color:#16a34a;font-weight:bold}',
      '@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}',
      '</style></head><body>',
      '<div class="container">',
      '<div class="header"><h1>TRACTOR REGISTRATION INVOICE</h1><p>Generated by Tractor Registration OCR System</p></div>',

      '<div class="s-title">1. PERSONAL INFORMATION</div>',
      '<div class="g2">',
      '<div class="row"><div class="label">Owner Name:</div><div class="value">' + (data.ownerName || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Father\'s Name:</div><div class="value">' + (data.fatherName || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Date of Birth:</div><div class="value">' + (data.dob || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Gender:</div><div class="value">' + (data.gender || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Aadhaar Number:</div><div class="value">' + (data.aadhaarNumber || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Mobile Number:</div><div class="value">' + (data.mobileNumber || '<span class="na">Not Available</span>') + '</div></div>',
      '</div>',

      '<div class="s-title green">2. ADDRESS INFORMATION</div>',
      '<div class="row"><div class="label">Address:</div><div class="value">' + (data.address || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="g2">',
      '<div class="row"><div class="label">Village:</div><div class="value">' + (data.village || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">District:</div><div class="value">' + (data.district || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">State:</div><div class="value">' + (data.state || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">PIN Code:</div><div class="value">' + (data.pin || '<span class="na">Not Available</span>') + '</div></div>',
      '</div>',

      '<div class="s-title amber">3. TRACTOR DETAILS</div>',
      '<div class="g2">',
      '<div class="row"><div class="label">Model:</div><div class="value">' + (data.model || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Colour:</div><div class="value">' + (data.colour || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Year:</div><div class="value">' + (data.year || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Engine Number:</div><div class="value">' + (data.engineNumber || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Chassis Number:</div><div class="value">' + (data.chassisNumber || '<span class="na">Not Available</span>') + '</div></div>',
      '</div>',
      (data.engineNumber && data.chassisNumber ? '<p class="v">&#10003; Chassis & Engine Numbers Verified</p>' : ''),

      '<div class="s-title purple">4. INVOICE INFORMATION</div>',
      '<div class="g2">',
      '<div class="row"><div class="label">Invoice Number:</div><div class="value">' + (data.invoiceNumber || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Invoice Date:</div><div class="value">' + (data.invoiceDate || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Invoice Amount:</div><div class="value">' + (data.invoiceAmount ? '&#8377; ' + data.invoiceAmount : '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Price (Ex-showroom):</div><div class="value">' + (data.price ? '&#8377; ' + data.price : '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Finance Bank:</div><div class="value">' + (data.financeBank || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">Dealership:</div><div class="value">' + (data.dealership || '<span class="na">Not Available</span>') + '</div></div>',
      '<div class="row"><div class="label">RTO Office:</div><div class="value">' + (data.rtoOffice || '<span class="na">Not Available</span>') + '</div></div>',
      '</div>',

      '<div class="footer">This is a computer-generated invoice. All data extracted via OCR from uploaded documents.<br>Generated on: ' + new Date().toLocaleString() + '</div>',
      '</div>',
      '<script>window.print();</script>',
      '</body></html>',
    ].join('\n');

    printWindow.document.write(html);
    printWindow.document.close();
  };

  const handleDownloadPDF = async () => {
    if (!invoiceRef.current) return;
    const jsPDFModule = await import('jspdf');
    const pdf = new jsPDFModule.default('p', 'mm', 'a4');
    const pw = pdf.internal.pageSize.getWidth();

    let y = 15;
    const section = (title: string, color: number[]) => {
      if (y > 270) { pdf.addPage(); y = 15; }
      pdf.setFillColor(color[0], color[1], color[2]);
      pdf.rect(15, y, pw - 30, 7, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(11);
      pdf.text(title, 20, y + 5);
      y += 12;
    };
    const f2 = (l1: string, v1: string, l2: string, v2: string) => {
      if (y > 275) { pdf.addPage(); y = 15; }
      pdf.setTextColor(80);
      pdf.setFontSize(9);
      pdf.text(l1, 15, y);
      pdf.setTextColor(30);
      pdf.setFontSize(10);
      pdf.text(v1 || 'Not Available', 65, y);
      pdf.setTextColor(80);
      pdf.setFontSize(9);
      pdf.text(l2, 110, y);
      pdf.setTextColor(30);
      pdf.setFontSize(10);
      pdf.text(v2 || 'Not Available', 160, y);
      y += 6;
    };

    pdf.setFontSize(18);
    pdf.setTextColor(37, 99, 235);
    pdf.text('TRACTOR REGISTRATION INVOICE', pw / 2, y, { align: 'center' });
    y += 8;
    pdf.setFontSize(9);
    pdf.setTextColor(120);
    pdf.text('Invoice #: ' + (data.invoiceNumber || 'DRAFT') + ' | Date: ' + (data.invoiceDate || new Date().toLocaleDateString()), pw / 2, y, { align: 'center' });
    y += 12;

    section('1. PERSONAL INFORMATION', [37, 99, 235]);
    f2('Owner Name:', data.ownerName, "Father's Name:", data.fatherName);
    f2('Date of Birth:', data.dob, 'Gender:', data.gender);
    f2('Aadhaar Number:', data.aadhaarNumber, 'Mobile Number:', data.mobileNumber);
    y += 3;

    section('2. ADDRESS INFORMATION', [22, 163, 74]);
    if (y > 260) { pdf.addPage(); y = 15; }
    pdf.setTextColor(80);
    pdf.setFontSize(9);
    pdf.text('Address:', 15, y);
    pdf.setTextColor(30);
    pdf.setFontSize(10);
    pdf.text(data.address || 'Not Available', 65, y);
    y += 8;
    f2('Village:', data.village, 'District:', data.district);
    f2('State:', data.state, 'PIN Code:', data.pin);
    y += 3;

    section('3. TRACTOR DETAILS', [217, 119, 6]);
    f2('Model:', data.model, 'Colour:', data.colour);
    f2('Year:', data.year, 'Engine Number:', data.engineNumber);
    pdf.setTextColor(80);
    pdf.setFontSize(9);
    pdf.text('Chassis Number:', 15, y);
    pdf.setTextColor(30);
    pdf.setFontSize(10);
    pdf.text(data.chassisNumber || 'Not Available', 65, y);
    y += 8;
    if (data.engineNumber && data.chassisNumber) {
      pdf.setTextColor(22, 163, 74);
      pdf.setFontSize(10);
      pdf.text('\u2713 Chassis & Engine Verified', pw / 2, y, { align: 'center' });
      y += 6;
    }
    y += 3;

    section('4. INVOICE INFORMATION', [147, 51, 234]);
    f2('Invoice Number:', data.invoiceNumber, 'Invoice Date:', data.invoiceDate);
    f2('Invoice Amount:', data.invoiceAmount ? '\u20B9 ' + data.invoiceAmount : 'Not Available', 'Price:', data.price ? '\u20B9 ' + data.price : 'Not Available');
    f2('Finance Bank:', data.financeBank, 'Dealership:', data.dealership);
    pdf.setTextColor(80);
    pdf.setFontSize(9);
    pdf.text('RTO Office:', 15, y);
    pdf.setTextColor(30);
    pdf.setFontSize(10);
    pdf.text(data.rtoOffice || 'Not Available', 65, y);
    y += 10;

    pdf.setTextColor(150);
    pdf.setFontSize(8);
    pdf.text('Generated on: ' + new Date().toLocaleString(), pw / 2, 285, { align: 'center' });

    pdf.save('tractor-invoice-' + (data.invoiceNumber || 'draft') + '.pdf');
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
          <FileText size={20} className="text-blue-600" />
          Invoice Preview
          <span className="text-xs font-normal text-gray-400 ml-1">(live, auto-synced)</span>
        </h3>
        <div className="flex gap-2 no-print">
          <button
            onClick={handleDownloadPDF}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded-lg flex items-center gap-1.5 transition-colors shadow-sm"
          >
            <Download size={14} />
            Download PDF
          </button>
          <button
            onClick={handlePrintInvoice}
            className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 text-sm rounded-lg flex items-center gap-1.5 transition-colors"
          >
            <Printer size={14} />
            Print
          </button>
        </div>
      </div>

      <div ref={invoiceRef} className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="text-center border-b-2 border-blue-600 px-6 py-4">
          <h2 className="text-xl font-bold text-blue-600">TRACTOR REGISTRATION INVOICE</h2>
          <p className="text-xs text-gray-500 mt-1">Generated by Tractor Registration OCR System</p>
        </div>

        <div className="p-6 space-y-5">
          {/* 1. Personal */}
          <div>
            <p className="text-sm font-bold text-white bg-blue-600 px-3 py-1.5 rounded mb-2">1. PERSONAL INFORMATION</p>
            <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm">
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Owner Name:</span><span className={'font-medium ' + (data.ownerName ? '' : 'text-gray-300 italic')}>{data.ownerName || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Father's Name:</span><span className={'font-medium ' + (data.fatherName ? '' : 'text-gray-300 italic')}>{data.fatherName || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Date of Birth:</span><span className={'font-medium ' + (data.dob ? '' : 'text-gray-300 italic')}>{data.dob || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Gender:</span><span className={'font-medium ' + (data.gender ? '' : 'text-gray-300 italic')}>{data.gender || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Aadhaar Number:</span><span className={'font-medium ' + (data.aadhaarNumber ? '' : 'text-gray-300 italic')}>{data.aadhaarNumber || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Mobile Number:</span><span className={'font-medium ' + (data.mobileNumber ? '' : 'text-gray-300 italic')}>{data.mobileNumber || 'Not Available'}</span></div>
            </div>
          </div>

          {/* 2. Address */}
          <div>
            <p className="text-sm font-bold text-white bg-green-600 px-3 py-1.5 rounded mb-2">2. ADDRESS INFORMATION</p>
            <div className="text-sm mb-1.5"><span className="text-gray-500">Address: </span><span className={'font-medium ' + (data.address ? '' : 'text-gray-300 italic')}>{data.address || 'Not Available'}</span></div>
            <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm">
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Village:</span><span className={'font-medium ' + (data.village ? '' : 'text-gray-300 italic')}>{data.village || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">District:</span><span className={'font-medium ' + (data.district ? '' : 'text-gray-300 italic')}>{data.district || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">State:</span><span className={'font-medium ' + (data.state ? '' : 'text-gray-300 italic')}>{data.state || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">PIN Code:</span><span className={'font-medium ' + (data.pin ? '' : 'text-gray-300 italic')}>{data.pin || 'Not Available'}</span></div>
            </div>
          </div>

          {/* 3. Tractor */}
          <div>
            <p className="text-sm font-bold text-white bg-amber-600 px-3 py-1.5 rounded mb-2">3. TRACTOR DETAILS</p>
            <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm">
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Model:</span><span className={'font-medium ' + (data.model ? '' : 'text-gray-300 italic')}>{data.model || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Colour:</span><span className={'font-medium ' + (data.colour ? '' : 'text-gray-300 italic')}>{data.colour || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Year:</span><span className={'font-medium ' + (data.year ? '' : 'text-gray-300 italic')}>{data.year || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Engine Number:</span><span className={'font-medium ' + (data.engineNumber ? '' : 'text-gray-300 italic')}>{data.engineNumber || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-28 shrink-0">Chassis Number:</span><span className={'font-medium ' + (data.chassisNumber ? '' : 'text-gray-300 italic')}>{data.chassisNumber || 'Not Available'}</span></div>
            </div>
            {data.engineNumber && data.chassisNumber && (
              <p className="text-green-600 text-xs font-semibold mt-2 flex items-center gap-1">&#10003; Chassis & Engine Numbers Verified</p>
            )}
          </div>

          {/* 4. Invoice */}
          <div>
            <p className="text-sm font-bold text-white bg-purple-600 px-3 py-1.5 rounded mb-2">4. INVOICE INFORMATION</p>
            <div className="grid grid-cols-2 gap-x-6 gap-y-1.5 text-sm">
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Invoice Number:</span><span className={'font-medium ' + (data.invoiceNumber ? '' : 'text-gray-300 italic')}>{data.invoiceNumber || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Invoice Date:</span><span className={'font-medium ' + (data.invoiceDate ? '' : 'text-gray-300 italic')}>{data.invoiceDate || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Invoice Amount:</span><span className={'font-medium ' + (data.invoiceAmount ? '' : 'text-gray-300 italic')}>{data.invoiceAmount ? '\u20B9 ' + data.invoiceAmount : 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Price (Ex-showroom):</span><span className={'font-medium ' + (data.price ? '' : 'text-gray-300 italic')}>{data.price ? '\u20B9 ' + data.price : 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Finance Bank:</span><span className={'font-medium ' + (data.financeBank ? '' : 'text-gray-300 italic')}>{data.financeBank || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">Dealership:</span><span className={'font-medium ' + (data.dealership ? '' : 'text-gray-300 italic')}>{data.dealership || 'Not Available'}</span></div>
              <div className="flex"><span className="text-gray-500 w-32 shrink-0">RTO Office:</span><span className={'font-medium ' + (data.rtoOffice ? '' : 'text-gray-300 italic')}>{data.rtoOffice || 'Not Available'}</span></div>
            </div>
          </div>

          <div className="text-center text-xs text-gray-400 border-t border-gray-100 pt-3">
            This is a computer-generated invoice. All data extracted via OCR from uploaded documents.<br />
            Generated on: {new Date().toLocaleString()}
          </div>
        </div>
      </div>
    </div>
  );
}